import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router, ActivatedRoute } from '@angular/router';
import { PatrolCompletionReportService } from '../services/patrol-completion-report.service';
import {
  PatrolCompletionReport,
  ReportType,
  ReportStatus,
  CompletionStatus
} from '../models/patrol-completion-report.model';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

@Component({
  selector: 'app-patrol-completion-report-detail',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <div class="patrol-completion-report-detail-container" *ngIf="report">
      <div class="page-header">
        <button class="btn-back" (click)="goBack()">
          <i class="material-icons">arrow_back</i>
          Back to Reports
        </button>
        <div class="header-actions">
          <button class="btn-export" (click)="exportReport('PDF')">
            <i class="material-icons">picture_as_pdf</i>
            Export PDF
          </button>
          <button class="btn-export" (click)="exportReport('EXCEL')">
            <i class="material-icons">table_chart</i>
            Export Excel
          </button>
          <button 
            class="btn-approve" 
            *ngIf="report.status === ReportStatus.GENERATED"
            (click)="approveReport()">
            <i class="material-icons">check_circle</i>
            Approve
          </button>
          <button class="btn-danger" (click)="deleteReport()">
            <i class="material-icons">delete</i>
            Delete
          </button>
        </div>
      </div>

      <div class="report-detail-card">
        <!-- Report Header -->
        <div class="report-header-section">
          <div class="report-icon-large">
            <i class="material-icons">assessment</i>
          </div>
          <div class="report-header-info">
            <h1>{{ report.reportName }}</h1>
            <div class="report-badges">
              <span class="badge-type">{{ getReportTypeLabel(report.reportType) }}</span>
              <span class="badge-status" [ngClass]="'status-' + report.status.toLowerCase()">
                {{ getStatusLabel(report.status) }}
              </span>
            </div>
            <div class="report-date-range">
              <i class="material-icons">calendar_today</i>
              <span>{{ formatDate(report.startDate) }} - {{ formatDate(report.endDate) }}</span>
            </div>
            <div class="report-generated-info">
              <i class="material-icons">person</i>
              <span>Generated by {{ report.generatedBy }} on {{ formatDateTime(report.generatedAt) }}</span>
            </div>
          </div>
        </div>

        <!-- Summary Statistics -->
        <div class="summary-section">
          <h2>
            <i class="material-icons">bar_chart</i>
            Summary Statistics
          </h2>
          <div class="summary-grid">
            <div class="summary-card">
              <div class="summary-icon total">
                <i class="material-icons">route</i>
              </div>
              <div class="summary-content">
                <div class="summary-value">{{ report.totalPatrols }}</div>
                <div class="summary-label">Total Patrols</div>
              </div>
            </div>
            <div class="summary-card">
              <div class="summary-icon completed">
                <i class="material-icons">check_circle</i>
              </div>
              <div class="summary-content">
                <div class="summary-value">{{ report.completedPatrols }}</div>
                <div class="summary-label">Completed</div>
                <div class="summary-percentage">{{ report.completionRate }}%</div>
              </div>
            </div>
            <div class="summary-card">
              <div class="summary-icon partial">
                <i class="material-icons">schedule</i>
              </div>
              <div class="summary-content">
                <div class="summary-value">{{ report.partialPatrols }}</div>
                <div class="summary-label">Partial</div>
              </div>
            </div>
            <div class="summary-card">
              <div class="summary-icon missed">
                <i class="material-icons">cancel</i>
              </div>
              <div class="summary-content">
                <div class="summary-value">{{ report.missedPatrols }}</div>
                <div class="summary-label">Missed</div>
              </div>
            </div>
            <div class="summary-card">
              <div class="summary-icon ontime">
                <i class="material-icons">timer</i>
              </div>
              <div class="summary-content">
                <div class="summary-value">{{ report.onTimeRate }}%</div>
                <div class="summary-label">On-Time Rate</div>
              </div>
            </div>
            <div class="summary-card">
              <div class="summary-icon average">
                <i class="material-icons">av_timer</i>
              </div>
              <div class="summary-content">
                <div class="summary-value">{{ report.averageCompletionTime }}</div>
                <div class="summary-label">Avg Time (min)</div>
              </div>
            </div>
          </div>
        </div>

        <!-- Checkpoint Statistics -->
        <div class="checkpoint-section">
          <h2>
            <i class="material-icons">place</i>
            Checkpoint Statistics
          </h2>
          <div class="checkpoint-stats-grid">
            <div class="checkpoint-stat-card">
              <div class="checkpoint-stat-icon scanned">
                <i class="material-icons">check_circle</i>
              </div>
              <div class="checkpoint-stat-content">
                <div class="checkpoint-stat-value">{{ report.totalCheckpointsScanned }}</div>
                <div class="checkpoint-stat-label">Scanned</div>
              </div>
            </div>
            <div class="checkpoint-stat-card">
              <div class="checkpoint-stat-icon missed">
                <i class="material-icons">cancel</i>
              </div>
              <div class="checkpoint-stat-content">
                <div class="checkpoint-stat-value">{{ report.totalCheckpointsMissed }}</div>
                <div class="checkpoint-stat-label">Missed</div>
              </div>
            </div>
            <div class="checkpoint-stat-card">
              <div class="checkpoint-stat-icon late">
                <i class="material-icons">schedule</i>
              </div>
              <div class="checkpoint-stat-content">
                <div class="checkpoint-stat-value">{{ report.totalCheckpointsLate }}</div>
                <div class="checkpoint-stat-label">Late</div>
              </div>
            </div>
          </div>
        </div>

        <!-- Route Statistics -->
        <div class="route-statistics-section" *ngIf="report.routeStatistics && report.routeStatistics.length > 0">
          <h2>
            <i class="material-icons">route</i>
            Route Performance
          </h2>
          <div class="statistics-table">
            <table>
              <thead>
                <tr>
                  <th>Route Name</th>
                  <th>Total Patrols</th>
                  <th>Completed</th>
                  <th>Completion Rate</th>
                  <th>Avg Time (min)</th>
                </tr>
              </thead>
              <tbody>
                <tr *ngFor="let stat of report.routeStatistics">
                  <td>{{ stat.routeName }}</td>
                  <td>{{ stat.totalPatrols }}</td>
                  <td>{{ stat.completedPatrols }}</td>
                  <td>
                    <div class="progress-bar">
                      <div class="progress-fill" [style.width.%]="stat.completionRate"></div>
                      <span class="progress-text">{{ stat.completionRate.toFixed(1) }}%</span>
                    </div>
                  </td>
                  <td>{{ stat.averageTime.toFixed(1) }}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <!-- Guard Statistics -->
        <div class="guard-statistics-section" *ngIf="report.guardStatistics && report.guardStatistics.length > 0">
          <h2>
            <i class="material-icons">person</i>
            Guard Performance
          </h2>
          <div class="statistics-table">
            <table>
              <thead>
                <tr>
                  <th>Guard Name</th>
                  <th>Total Patrols</th>
                  <th>Completed</th>
                  <th>Completion Rate</th>
                  <th>On-Time Rate</th>
                  <th>Avg Time (min)</th>
                </tr>
              </thead>
              <tbody>
                <tr *ngFor="let stat of report.guardStatistics">
                  <td>{{ stat.guardName }}</td>
                  <td>{{ stat.totalPatrols }}</td>
                  <td>{{ stat.completedPatrols }}</td>
                  <td>
                    <div class="progress-bar">
                      <div class="progress-fill" [style.width.%]="stat.completionRate"></div>
                      <span class="progress-text">{{ stat.completionRate.toFixed(1) }}%</span>
                    </div>
                  </td>
                  <td>
                    <div class="progress-bar">
                      <div class="progress-fill" [style.width.%]="stat.onTimeRate"></div>
                      <span class="progress-text">{{ stat.onTimeRate.toFixed(1) }}%</span>
                    </div>
                  </td>
                  <td>{{ stat.averageTime.toFixed(1) }}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <!-- Daily Statistics -->
        <div class="daily-statistics-section" *ngIf="report.dailyStatistics && report.dailyStatistics.length > 0">
          <h2>
            <i class="material-icons">calendar_view_week</i>
            Daily Performance
          </h2>
          <div class="statistics-table">
            <table>
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Total Patrols</th>
                  <th>Completed</th>
                  <th>Completion Rate</th>
                </tr>
              </thead>
              <tbody>
                <tr *ngFor="let stat of report.dailyStatistics">
                  <td>{{ formatDate(stat.date) }}</td>
                  <td>{{ stat.totalPatrols }}</td>
                  <td>{{ stat.completedPatrols }}</td>
                  <td>
                    <div class="progress-bar">
                      <div class="progress-fill" [style.width.%]="stat.completionRate"></div>
                      <span class="progress-text">{{ stat.completionRate.toFixed(1) }}%</span>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <!-- Issues Summary -->
        <div class="issues-section" *ngIf="report.totalIssues > 0">
          <h2>
            <i class="material-icons">warning</i>
            Issues Summary
          </h2>
          <div class="issues-grid">
            <div class="issue-card">
              <div class="issue-icon total">
                <i class="material-icons">error_outline</i>
              </div>
              <div class="issue-content">
                <div class="issue-value">{{ report.totalIssues }}</div>
                <div class="issue-label">Total Issues</div>
              </div>
            </div>
            <div class="issue-card critical">
              <div class="issue-icon critical">
                <i class="material-icons">error</i>
              </div>
              <div class="issue-content">
                <div class="issue-value">{{ report.criticalIssues }}</div>
                <div class="issue-label">Critical Issues</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Loading State -->
    <div class="loading-state" *ngIf="isLoading">
      <i class="material-icons">hourglass_empty</i>
      <p>Loading report details...</p>
    </div>

    <!-- Error State -->
    <div class="error-state" *ngIf="!isLoading && !report">
      <i class="material-icons">error_outline</i>
      <p>{{ loadError || 'Report not found' }}</p>
      <button class="btn-primary" (click)="goBack()">Back to Reports</button>
    </div>
  `,
  styles: [`
    .patrol-completion-report-detail-container {
      padding: 24px;
      max-width: 1400px;
      margin: 0 auto;
    }

    .page-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 24px;
      flex-wrap: wrap;
      gap: 16px;
    }

    .btn-back {
      padding: 10px 20px;
      background: #f5f5f5;
      color: #2c3e50;
      border: 2px solid #e0e0e0;
      border-radius: 8px;
      font-size: 14px;
      font-weight: 600;
      cursor: pointer;
      display: flex;
      align-items: center;
      gap: 8px;
      transition: all 0.2s;
    }

    .btn-back:hover {
      background: #e0e0e0;
    }

    .header-actions {
      display: flex;
      gap: 12px;
      flex-wrap: wrap;
    }

    .btn-export,
    .btn-approve,
    .btn-danger {
      padding: 10px 20px;
      border: none;
      border-radius: 8px;
      font-size: 14px;
      font-weight: 600;
      cursor: pointer;
      display: flex;
      align-items: center;
      gap: 8px;
      transition: all 0.2s;
    }

    .btn-export {
      background: #17a2b8;
      color: white;
    }

    .btn-export:hover {
      background: #138496;
    }

    .btn-approve {
      background: #28a745;
      color: white;
    }

    .btn-approve:hover {
      background: #218838;
    }

    .btn-danger {
      background: #dc3545;
      color: white;
    }

    .btn-danger:hover {
      background: #c82333;
    }

    .report-detail-card {
      background: white;
      border-radius: 12px;
      padding: 32px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    }

    .report-header-section {
      display: flex;
      gap: 24px;
      margin-bottom: 32px;
      padding-bottom: 24px;
      border-bottom: 2px solid #f0f0f0;
    }

    .report-icon-large {
      width: 80px;
      height: 80px;
      border-radius: 16px;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      display: flex;
      align-items: center;
      justify-content: center;
      color: white;
      font-size: 40px;
      flex-shrink: 0;
    }

    .report-header-info {
      flex: 1;
    }

    .report-header-info h1 {
      margin: 0 0 12px 0;
      font-size: 32px;
      color: #2c3e50;
    }

    .report-badges {
      display: flex;
      gap: 8px;
      flex-wrap: wrap;
      margin-bottom: 12px;
    }

    .badge-type,
    .badge-status {
      padding: 6px 12px;
      border-radius: 6px;
      font-size: 12px;
      font-weight: 600;
      text-transform: uppercase;
    }

    .badge-type {
      background: #e7f3ff;
      color: #004085;
    }

    .badge-status.status-generated {
      background: #d1ecf1;
      color: #0c5460;
    }

    .badge-status.status-approved {
      background: #d4edda;
      color: #155724;
    }

    .report-date-range,
    .report-generated-info {
      display: flex;
      align-items: center;
      gap: 8px;
      margin-top: 8px;
      font-size: 14px;
      color: #7f8c8d;
    }

    .summary-section,
    .checkpoint-section,
    .route-statistics-section,
    .guard-statistics-section,
    .daily-statistics-section,
    .issues-section {
      margin-bottom: 32px;
      padding-top: 24px;
      border-top: 2px solid #f0f0f0;
    }

    .summary-section h2,
    .checkpoint-section h2,
    .route-statistics-section h2,
    .guard-statistics-section h2,
    .daily-statistics-section h2,
    .issues-section h2 {
      font-size: 20px;
      margin: 0 0 20px 0;
      color: #2c3e50;
      display: flex;
      align-items: center;
      gap: 8px;
    }

    .summary-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 20px;
    }

    .summary-card {
      background: #f8f9fa;
      border-radius: 12px;
      padding: 20px;
      display: flex;
      gap: 16px;
      align-items: center;
    }

    .summary-icon {
      width: 56px;
      height: 56px;
      border-radius: 12px;
      display: flex;
      align-items: center;
      justify-content: center;
      color: white;
      font-size: 28px;
      flex-shrink: 0;
    }

    .summary-icon.total { background: #667eea; }
    .summary-icon.completed { background: #28a745; }
    .summary-icon.partial { background: #ffc107; }
    .summary-icon.missed { background: #dc3545; }
    .summary-icon.ontime { background: #17a2b8; }
    .summary-icon.average { background: #6c757d; }

    .summary-content {
      flex: 1;
    }

    .summary-value {
      font-size: 28px;
      font-weight: 700;
      color: #2c3e50;
      margin-bottom: 4px;
    }

    .summary-label {
      font-size: 13px;
      color: #7f8c8d;
      text-transform: uppercase;
      font-weight: 600;
    }

    .summary-percentage {
      font-size: 12px;
      color: #28a745;
      margin-top: 4px;
    }

    .checkpoint-stats-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 20px;
    }

    .checkpoint-stat-card {
      background: #f8f9fa;
      border-radius: 12px;
      padding: 20px;
      display: flex;
      gap: 16px;
      align-items: center;
    }

    .checkpoint-stat-icon {
      width: 56px;
      height: 56px;
      border-radius: 12px;
      display: flex;
      align-items: center;
      justify-content: center;
      color: white;
      font-size: 28px;
      flex-shrink: 0;
    }

    .checkpoint-stat-icon.scanned { background: #28a745; }
    .checkpoint-stat-icon.missed { background: #dc3545; }
    .checkpoint-stat-icon.late { background: #ffc107; }

    .checkpoint-stat-content {
      flex: 1;
    }

    .checkpoint-stat-value {
      font-size: 28px;
      font-weight: 700;
      color: #2c3e50;
      margin-bottom: 4px;
    }

    .checkpoint-stat-label {
      font-size: 13px;
      color: #7f8c8d;
      text-transform: uppercase;
      font-weight: 600;
    }

    .statistics-table {
      overflow-x: auto;
    }

    .statistics-table table {
      width: 100%;
      border-collapse: collapse;
      background: white;
      border-radius: 8px;
      overflow: hidden;
    }

    .statistics-table thead {
      background: #f8f9fa;
    }

    .statistics-table th {
      padding: 16px;
      text-align: left;
      font-size: 13px;
      font-weight: 600;
      color: #2c3e50;
      text-transform: uppercase;
      border-bottom: 2px solid #e0e0e0;
    }

    .statistics-table td {
      padding: 16px;
      border-bottom: 1px solid #f0f0f0;
      font-size: 14px;
      color: #2c3e50;
    }

    .statistics-table tbody tr:hover {
      background: #f8f9fa;
    }

    .progress-bar {
      position: relative;
      width: 100%;
      height: 24px;
      background: #e0e0e0;
      border-radius: 12px;
      overflow: hidden;
    }

    .progress-fill {
      position: absolute;
      left: 0;
      top: 0;
      height: 100%;
      background: linear-gradient(90deg, #28a745 0%, #20c997 100%);
      transition: width 0.3s ease;
    }

    .progress-text {
      position: absolute;
      left: 50%;
      top: 50%;
      transform: translate(-50%, -50%);
      font-size: 11px;
      font-weight: 600;
      color: #2c3e50;
      z-index: 1;
    }

    .issues-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 20px;
    }

    .issue-card {
      background: #f8f9fa;
      border-radius: 12px;
      padding: 20px;
      display: flex;
      gap: 16px;
      align-items: center;
    }

    .issue-card.critical {
      background: #fff5f5;
      border-left: 4px solid #dc3545;
    }

    .issue-icon {
      width: 56px;
      height: 56px;
      border-radius: 12px;
      display: flex;
      align-items: center;
      justify-content: center;
      color: white;
      font-size: 28px;
      flex-shrink: 0;
    }

    .issue-icon.total { background: #ffc107; }
    .issue-icon.critical { background: #dc3545; }

    .issue-content {
      flex: 1;
    }

    .issue-value {
      font-size: 28px;
      font-weight: 700;
      color: #2c3e50;
      margin-bottom: 4px;
    }

    .issue-label {
      font-size: 13px;
      color: #7f8c8d;
      text-transform: uppercase;
      font-weight: 600;
    }

    .loading-state,
    .error-state {
      text-align: center;
      padding: 60px 20px;
      color: #7f8c8d;
    }

    .loading-state .material-icons,
    .error-state .material-icons {
      font-size: 64px;
      margin-bottom: 16px;
      color: #ddd;
    }

    .btn-primary {
      padding: 12px 24px;
      background: #667eea;
      color: white;
      border: none;
      border-radius: 8px;
      font-size: 14px;
      font-weight: 600;
      cursor: pointer;
      transition: all 0.2s;
    }

    .btn-primary:hover {
      background: #5568d3;
    }

    @media (max-width: 768px) {
      .report-header-section {
        flex-direction: column;
      }

      .summary-grid,
      .checkpoint-stats-grid,
      .issues-grid {
        grid-template-columns: 1fr;
      }
    }
  `]
})
export class PatrolCompletionReportDetailComponent implements OnInit, OnDestroy {
  report: PatrolCompletionReport | null = null;
  isLoading = false;
  loadError = '';

  ReportType = ReportType;
  ReportStatus = ReportStatus;

  private destroy$ = new Subject<void>();
  private reportId: string | null = null;

  constructor(
    private reportService: PatrolCompletionReportService,
    private router: Router,
    private activatedRoute: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this.activatedRoute.params.subscribe(params => {
      if (params['id']) {
        this.reportId = params['id'];
        if (this.reportId) {
          this.loadReport(this.reportId);
        }
      }
    });
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  loadReport(id: string): void {
    this.isLoading = true;
    this.loadError = '';
    this.report = null;

    this.reportService.getReportById(id)
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: (report) => {
          this.report = report;
          this.isLoading = false;
          if (!report) {
            this.loadError = 'Report not found';
          }
        },
        error: (error) => {
          console.error('Error loading report:', error);
          this.loadError = 'Failed to load report from the API. Ensure the backend is running.';
          this.isLoading = false;
        }
      });
  }

  goBack(): void {
    this.router.navigate(['/admin/guard-patrol/completion-reports']);
  }

  exportReport(format: 'PDF' | 'EXCEL' | 'CSV'): void {
    if (this.report) {
      this.reportService.exportReport(this.report.id, format)
        .pipe(takeUntil(this.destroy$))
        .subscribe({
          next: (blob) => {
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            const ext =
              format === 'PDF' ? (blob.type.includes('pdf') ? 'pdf' : 'html') : 'csv';
            a.download = `${this.report!.reportName.replace(/[\\/:*?"<>|]+/g, '_')}.${ext}`;
            a.click();
            window.URL.revokeObjectURL(url);
          },
          error: (error) => {
            console.error('Error exporting report:', error);
            window.alert('Error exporting report');
          }
        });
    }
  }

  approveReport(): void {
    if (this.report && window.confirm(`Approve the report "${this.report.reportName}"?`)) {
      this.reportService.updateReportStatus(this.report.id, ReportStatus.APPROVED)
        .pipe(takeUntil(this.destroy$))
        .subscribe({
          next: (success) => {
            if (success && this.reportId) {
              this.loadReport(this.reportId);
            } else {
              window.alert('Error approving report');
            }
          },
          error: (error) => {
            console.error('Error approving report:', error);
            window.alert('Error approving report');
          }
        });
    }
  }

  deleteReport(): void {
    if (this.report && window.confirm(`Are you sure you want to delete the report "${this.report.reportName}"?`)) {
      this.reportService.deleteReport(this.report.id)
        .pipe(takeUntil(this.destroy$))
        .subscribe({
          next: (success) => {
            if (success) {
              this.goBack();
            } else {
              window.alert('Error deleting report');
            }
          },
          error: (error) => {
            console.error('Error deleting report:', error);
            window.alert('Error deleting report');
          }
        });
    }
  }

  getReportTypeLabel(type: ReportType): string {
    const labels: { [key: string]: string } = {
      'DAILY': 'Daily',
      'WEEKLY': 'Weekly',
      'MONTHLY': 'Monthly',
      'CUSTOM': 'Custom',
      'ROUTE_SPECIFIC': 'Route Specific',
      'GUARD_SPECIFIC': 'Guard Specific'
    };
    return labels[type] || type;
  }

  getStatusLabel(status: ReportStatus): string {
    const labels: { [key: string]: string } = {
      'DRAFT': 'Draft',
      'GENERATED': 'Generated',
      'APPROVED': 'Approved',
      'ARCHIVED': 'Archived'
    };
    return labels[status] || status;
  }

  formatDate(date: Date): string {
    return new Date(date).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric'
    });
  }

  formatDateTime(date: Date): string {
    return new Date(date).toLocaleString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: 'numeric',
      minute: '2-digit'
    });
  }
}

